# Generated by Django 6.0 on 2026-01-21 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('highlighted_text', models.TextField()),
                ('image_path', models.ImageField(upload_to='evidence_artifacts/')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authority', models.CharField(choices=[('BNM', 'Bank Negara Malaysia'), ('AAOIFI', 'AAOIFI'), ('SC', 'Securities Commission'), ('IIFM', 'IIFM'), ('FATWA', 'General Fatwas'), ('IIFA', 'International Islamic Fiqh Academy')], max_length=20)),
                ('file_path', models.FileField(upload_to='source_documents/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], max_length=10)),
                ('text_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='evidence_engine.chatsession')),
                ('evidence_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='evidence_engine.evidenceartifact')),
            ],
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='source_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='evidence_engine.sourcedocument'),
        ),
    ]
