# Generated by Django 5.2.10 on 2026-01-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_engine', '0002_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='is_ingested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original URL of the document', max_length=500, null=True),
        ),
    ]
